### PR TITLE
Fix typescript preset issue where defaults includes are overwritten

### LINKED ISSUE #79: TypeScript Preset 1.2.0 not working w/ HTML framework
After upgrading the TypeScript Preset from 1.1.0 to 1.2.0, we got a lot of errors (unexpected token). The TypeScript code cannot be parsed anymore. You can reproduce by cloning [this repository](https://github.com/darondel/storybook-html-playground):

- Current version uses 1.1.0 => it works.
- Try to upgrade to 1.2.0 => it fails.

Note that if I uses the 1.1.0 version with the new beta version of Storybook (5.3), it fails as well.

Something is missing from my configuration?

### PR DESCRIPTION
**Pull request by T0MASD**
instead of overwriting the existing includes (that may have come from webpack config), append them, like it's done with other options using rest parameter.

Fixes #79 #65

### CODE REVIEW

**Comment by mrmckeb** [comment]
Hi @T0MASD, can you explain this a little further please? :) What you're doing - from what I can see - is requiring includes to be an object with an `includes` key, right?

**Comment by T0MASD** [comment]
Hi @mrmckeb cheers for taking a look. Apologies I haven't clearly explained the change. This basically initializes deault includes as empy array (so it's not undefined), similar to how `tsLoaderOptions` defaults to `{transpileOnly: true }`. Includes are then appended to running webpack config (they were getting replaced previously) causing issues in #79

**Comment by mrmckeb** [comment]
Thanks @T0MASD, what I'm confused about is why `includes` is now being spread?
https://github.com/storybookjs/presets/pull/83/files#diff-de1cea8c892f52e17267593cfab2925bR36

This looks like a mistake to me, but I could be misunderstanding this PR.

**Comment by T0MASD** [comment]
@mrmckeb you were right, using spread for includes was bad. I have updated the PR.

It now matches default includes and excludes of mjs|jsx (babel-loader). 
```
[
  {
    test: /\.(mjs|jsx?)$/,
    use: [ [Object] ],
    include: [
      '/storybook/storybook-html-playground'
    ],
    exclude: [
      /storybook/storybook-html-playground/node_modules'
    ]
  },
  { test: /\.md$/, use: [ [Object] ] },
  { test: /\.html$/, use: [ [Object] ] },
  {
    test: /\.tsx?$/,
    use: [ [Object], [Object] ],
    include: [
      '/storybook/storybook-html-playground'
    ],
    exclude: [
      '/storybook/storybook-html-playground/node_modules'
    ]
  }
]
``` 
I wasn't sure if it was better to import utils from core/dist/server/config/utils.js and use:
```
  include: _utils.includePaths,
  exclude: _utils.excludePaths
```

Any feedback is appreciated

**Comment by mrmckeb** [comment]
I'm OK with this overall, thanks @T0MASD - @shilman, any thoughts?

**Comment by mobinni** [comment]
Should we default this to reading the `include` from your `tsconfig` if available?

**Comment by alaboudi** [comment]
Yes, this is an issue. Please merge in. I'm aslo a fan of using the `include` key from the tsconfig file. That possibly makes more sense.

**Comment by mrmckeb** [comment]
@shilman and I discussed this and we think that there should be no defaults, this should be undefined if not user-provided.

**Comment by shilman** [comment]
Merged #106 instead. Closing.

**Pull request closed without merging**
