### PR TITLE
Delete preset-storysource

### PR DESCRIPTION
**Pull request by shilman**
Issue: #39 

This belongs in the addon itself (IMHO) and its presence is causing confusion.

### CODE REVIEW

**Comment by jerriclynsjohn** [comment]
I'm hoping this will get added into the add-on itself, If that's the case use `loaders: [require.resolve('@storybook/source-loader')],` as i see that in the deleted files it uses the deprecated loader.

**Comment by shilman** [comment]
@jerriclynsjohn I'd gladly accept a PR on the addon!

**Comment by jerriclynsjohn** [comment]
> @jerriclynsjohn I'd gladly accept a PR on the addon!

Since you do not want this is the presets repo, how do you think the file structure should be in the storysource addon folder, any standards that I'm missing.

**Comment by shilman** [comment]
@jerriclynsjohn Thanks for volunteering! I would make a `./preset.js` entry that exports `./dist/preset.js` (which is generated from `./src/preset.js`). But happy to review any solution :)

**Pull request merged**
