### PR TITLE
IE11: Add more libs to transpile

### PR DESCRIPTION
**Pull request by tooppaaa**
Issue: #190
Storybook: https://github.com/storybookjs/storybook/issues/12179

### CODE REVIEW

**Comment by tooppaaa** [comment]
@shilman, looks like CI si failling. Should we use this to kill this repo and move presets back to main repo ?

**Comment by shilman** [comment]
@tooppaaa yes, let's discuss on monday?

**Comment by reessm01** [comment]
I integrated his changes locally and was able to get IE11 running. I'm using that as a workaround in the mean time. If this PR needs any support please let me know.

**Comment by leepowelldev** [comment]
Not sure if you want to add `@pmmmwh/react-refresh-webpack-plugin` as I'm seeing ES6 exposed in that package too a of 0.4.3 release. I believe its fixed for the next release though.

**Comment by tooppaaa** [comment]
@leepowelldev I tried adding it but it's injecting code outside of compilation. 
It will be resolved in 0.5.x if I'm right which is in beta for the moment.

@shilman, I think we could ship that one ?

**Comment by seanparmelee** [comment]
For anyone else interested in this change, it's been moved to an addon: https://storybook.js.org/addons/@storybook/addon-ie11/

**Comment by mt9eet** [comment]
I tried adding `@storybook/addon-ie11` to my project and it does not seem to work as I'm getting error in the acorn-jsx syntax in IE. I'm just wondering if it's on my end or the addon is not ready 🙂

**Comment by seanparmelee** [comment]
> I tried adding `@storybook/addon-ie11` to my project and it does not seem to work as I'm getting error in the acorn-jsx syntax in IE. I'm just wondering if it's on my end or the addon is not ready 🙂

In my case, it was the `color-convert` dependency that was causing the problem, but FWIW it looks like `acorn-jsx` is one of the dependencies that's configured to be transpiled as well: https://github.com/storybookjs/addon-ie11/blob/ef27f126f1e44b31da9c22918a9643ac086f6c1a/src/preset.ts#L42

**Comment by tooppaaa** [comment]
> For anyone else interested in this change, it's been moved to an addon: https://storybook.js.org/addons/@storybook/addon-ie11/

Closing.

**Pull request closed without merging**
