### PR TITLE
Example for preset-typescript with vue-cli and potential fix

### PR DESCRIPTION
**Pull request by graup**
I added another example, which is very close to what vue-cli produces when you initialize a new project with typescript and babel. It doesn't work with the current version (3.0.0) – see #121 

While digging around, it seems the babel-loader doesn't apply the custom babel config correctly (which in this case is needed for the class properties and decorators), or it does so at the wrong time, or something.

From the previous version, I salvaged the code that added ts-loader, and sure enough, that works. I added this code back in for testing. Ideally, we don't need it, but if we can't find another solution, this may be the easiest fix.

/edit: when using `@vue/cli-plugin-babel/preset`, you don't need `babel-preset-typescript-vue` anymore, but we should probably leave it in for folks who don't have their own babel config. It doesn't seem to conflict.

### CODE REVIEW

**Comment by shilman** [comment]
Thanks for looking into this @graup! 

Any idea why babel is failing? Does this code first run babel on the user's code and THEN run typescript on the output?

I know this is already a fallback, but if we want people to switch to babel, I'd suggest only add this if `framework` is `"vue"`, or maybe if the user explicitly defines `tsLoaderOptions` (opt-in).

WDYT? cc @Aaron-Pool @mrmckeb

**Comment by graup** [comment]
I'm not sure. As far as I understand, the webpack chain is:

(.vue) vue-loader -> (.ts) ts-loader -> (.js) babel-loader

This seems to go back to the issue that @mrmckeb was fighting – maybe there just isn't any sensible way to use Vue's SCF without ts-loader :/

**Comment by shilman** [comment]
OK, I'm cool with that:
1) if that's the best we can come up with
2) if we make sure that `ts-loader` is either opt-in, or only applied in the "vue" case

Having both loaders running in React will be confusing and possibly problematic.

**Comment by mrmckeb** [comment]
Sorry guys, I checked out for a few days. 

I'll chat to @shilman on this and get back to you ASAP. Sorry, we did try to verify that this was working with Vue, but apparently didn't test thoroughly enough.

**Comment by shilman** [comment]
@graup what do you think about building this into the vue framework preset in `@storybook/vue`? i talked to @mrmckeb and he said the vue typescript story is pretty unique and would justify that, rather than putting it into the preset.

**Comment by rcidaleassumpo** [comment]
Hi, since this is merged, does that mean that in the near future the preset-typescript will be working with vue, or ? What's the step to make typescript and vue work together ? Thank you.

**Comment by dgreene1** [comment]
Btws, the readme still describes that you can pass a ts-loader config object even though it appears that ts-loader was removed in a prior PR but is being proposed to be brought back in this PR.

**Comment by mrmckeb** [comment]
Sorry I should update here. I've had a discussion with @graup and he agrees that we should move this to the framework.

@shilman that means we could close this off in favour of adding this functionality to the Vue framework preset. @graup could you do that work? Or I can take a look?

**Comment by shilman** [comment]
SGTM. Closing!

**Pull request closed without merging**
