### PR TITLE
Fix react-script package directory resolution

### LINKED ISSUE #58: preset-create-react-app fails to resolve react-scripts in RushJS monorepo with PNPM
I get the following error:
`stack: "Error: Cannot find module 'monorepodir/libraries/ui/node_modules/config/webpack.config'\n" +`

I can fix it by manually commenting out line 27-39 in 
`node_modules/@storybook/preset-create-react-app/helpers/getReactScriptsPath.js`

Seems like `/node_modules/.bin/react-scripts` isn't symlinked like the preset expects which makes it resolve to an incorrect directory

### PR DESCRIPTION
**Pull request by remorses**
Given that the `react-scripts` package has no `main` field i am resolving to package.json

Fix #58

### CODE REVIEW

**Comment by mrmckeb** [comment]
Hi @remorses, if this will work for all operating systems, can we remove the unnecessary code too?

Thanks for this!

**Comment by remorses** [comment]
OK i removed the unused code

**Comment by mrmckeb** [comment]
Hi @remorses, this behaviour is complex - agreed - but it's on purpose. People are (kind of) encouraged to fork `react-scripts` when they want to add custom behaviour, and this logic resolves those custom forks.

This PR unfortunately breaks that behaviour... I hope that makes sense?

**Comment by pseudo-su** [comment]
> People are (kind of) encouraged to fork react-scripts when they want to add custom behaviour, and this logic resolves those custom forks.

Would it be better to just provide a config option on `@storybook/preset-create-react-app` to allow users who need to specify a custom/forked `react-scripts` library to do so?

Something like:

```js
{
  name: "@storybook/preset-create-react-app",
  options: {
    reactScriptsLib: require.resolve("my-custom-react-scripts"),
  },
}
```

The custom code for magically resolving these libraries could be kept for the time being (and possibly removed in a future major version release?) while still keeping this change to fix it for anyone who's using the default `react-scripts` lib:

```
const scriptsPath = require.resolve('react-scripts/package.json');
return scriptsPath;
return dirname(scriptsPath);
```

**Pull request closed without merging**
