### PR TITLE
adding readme info for preset-storysource, and the presets repo root …

### PR DESCRIPTION
**Pull request by joeycozza**
…README

### CODE REVIEW

**Comment by joeycozza** [comment]
So I tested this all locally with npm linking, and it worked great. I would love to see the preset-storysource published to npm!

**Comment by joeycozza** [comment]
Shilman mentioned that there is some discussion about the "correct" place to put this preset, and that it may be moved to source-loader (or already has). Either way, no big deal. I'm just willing to help out where I can.

**Comment by shilman** [comment]
Thanks @joeycozza. I'm gonna merge this in, since it looks great and will be relevant no matter what happens to this package. But I'm going to hold off on publishing until we've worked out whether we'll publish this:
- as part of `@storybook/source-loader`
- as part of `@storybook/addon-storysource`
- as a standalone package

cc @igor-dv @Hypnosphi @libetl

**Comment by libetl** [comment]
Yes Michael and @joeycozza  I saw that one already. Thanks

**Pull request merged**
