### PR TITLE
Remove `react-typescript-docgen-loader` from `preset-typescript`

### PR DESCRIPTION
**Pull request by shilman**
## What I did

Removed all instances of `react-typescript-docgen-loader` from `preset-typescript` per https://github.com/storybookjs/storybook/issues/8337 since `preset-typescript` should be for all frameworks, not just react.

Incremented major version change

There's an accompanying PR that adds it to `addon-docs`: https://github.com/storybookjs/storybook/pull/8984

### CODE REVIEW

**Comment by mrmckeb** [comment]
Looks great!

**Comment by shilman** [comment]
@patricklafrance I'll merge & release once storybookjs/storybook#8984 is ready

**Comment by patricklafrance** [comment]
@shilman 👍

**Comment by graup** [comment]
@shilman can we get this merged? I'm working on an easier vue+ts setup and this is would help simplify things.

**Pull request merged**
